/**
 * 바이낸스 USDT 현물 워치리스트 (백엔드 core/symbol_lists.py 와 동기화)
 */
export const WATCHLIST_SYMBOLS = [
  'BTC/USDT',
  'ETH/USDT',
  'BNB/USDT',
  'SOL/USDT',
  'XRP/USDT',
  'ADA/USDT',
  'DOGE/USDT',
  'AVAX/USDT',
  'DOT/USDT',
  'LINK/USDT',
  'LTC/USDT',
  'TRX/USDT',
  'ATOM/USDT',
  'NEAR/USDT',
  'ARB/USDT',
  'OP/USDT',
  'UNI/USDT',
  'APT/USDT',
  'SUI/USDT',
  'INJ/USDT',
  'FIL/USDT',
  'TIA/USDT',
  'WLD/USDT',
  'SHIB/USDT',
  'ETC/USDT',
  'AAVE/USDT',
  'HBAR/USDT',
  'ICP/USDT',
  'STX/USDT',
  'TON/USDT',
  'BCH/USDT',
  'RENDER/USDT',
] as const
